name: Hotfix to prod workflow
on:
  pull_request:
    branches:
      - prod
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true && github.head_ref != 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        run: echo "${{ toJSON(github) }}";
      - name: Create a pull request containing hotfix to main
        run: gh pr create -B main -H ${{ github.head_ref }} --title 'Merge prod hotfix ${{ github.head_ref }} into main' --body 'Created by Github action'
        env:
          GH_TOKEN: ${{ github.token }}

# on:
#   pull_request:
#     branches:
#       - prod
#     types:
#       - closed
# jobs:
#   if_merged:
#     if: github.event.pull_request.merged == true && github.base_ref != 'main'
#     runs-on: ubuntu-latest
#     steps:
#       - name: Create a pull request containing hotfix to main
#         run: echo "$GITHUB_TOKEN";
#         # run: gh pr create -B main -H branch_to_merge --title 'Merge branch_to_merge into main' --body 'Created by Github action'
#         env:
#           GITHUB_TOKEN: test
#           # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
