name: New milestone workflow
on:
  workflow_dispatch:
  milestone:
    types: [opened]
jobs:
  second-job:
    env:
      GH_TOKEN: ${{ github.token }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Run script file
        id: bump-version
        run: |
          chmod +x ./scripts/increment-version.sh
          echo "NEW_VERSION=$(./scripts/increment-version.sh)" >> $GITHUB_OUTPUT
        shell: bash

      - name: Create new branch and push
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git switch -c ${{ steps.bump-version.outputs.NEW_VERSION }} main
          git add .
          git commit -m "bump version to ${{ steps.bump-version.outputs.NEW_VERSION }}"
          git tag -a ${{ steps.bump-version.outputs.NEW_VERSION }} HEAD
          git push origin ${{ steps.bump-version.outputs.NEW_VERSION }}
          git push -u origin ${{ steps.bump-version.outputs.NEW_VERSION }}

      - name: Create a pull request containing hotfix to main
        run: gh pr create -B main -H ${{ steps.bump-version.outputs.NEW_VERSION }} --title 'Bump version to ${{ steps.bump-version.outputs.NEW_VERSION }}' --body 'Created by Github action'
