name: First workflow
on: push
jobs:
  second-job:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version-file: .node-version

      - name: Lint
        run: npm run lint

      - name: Install
        run: npm install